# This .yml file is used to specify the conda environment that should be loaded into the binder instance
name: pymcx
dependencies:
  - python=3.7
  - matplotlib
  - scipy
  - numpy
  - jupyter
  - notebook
  - sympy
  - pip
  - pip:
    - "git+git://github.com/ianhbell/mcx.git"